language: python

python:

  - 3.5

env:
  - pipenv

install:
  - pipenv install


script:

 - py.test --cov=tests

deploy:
  provider: openshift
  user: developer
  password: tshula19
  domain: http://flaskapplication-flask-app.192.168.99.103.nip.io/
  skip_cleanup: true
on:
  all_branches: true
