language: python

python:
  - 3.5
  - 3.7

env:
  - pipenv

install:
  - pipenv install


script:
 - py.test --cov=tests


# notifications:
#   email:
#     - xolani@kineticskunk.com



    
>>>>>>> bd269a8db210daa4fac5bd850e0aec26e07e4c68
