language: python

python:

  - 3.5



  env:
  - pipenv


install:
  - pipenv install
  - pip install -r requirements.txt



script:

 - py.test --cov=tests


# notifications:
#   email:
#     - xolani@kineticskunk.com
