language: python

python:

  - 3.5

env:
  - pipenv

install:
  - pipenv install

script:
 - py.test --cov=tests

deploy:
  provider: openshift
  # Configure these values on your TravisCI 'Repository Settings' page:
  # http://docs.travis-ci.com/user/environment-variables/#Using-Settings
  user: lwando@kineticskunk.com
  password: pa55word3
  app: elldee
  domain: https://192.168.99.102:8443/console
  on: lwando

repo: kineticskunk/flaskapplication
