language: python

python:

  - 3.5


install:
  # - pip install -r requirements.txt
  - pipenv install
  

script:
 - py.test --cov=tests

deploy:
  provider: openshift
  user: "Ludwej"
  password: "12345" # can be encrypted
  domain: "YOUR OPENSHIFT DOMAIN"
