language: python

python:

  - 3.5

env:
  - pipenv

install:
  - pipenv install


script:

 - py.test --cov=tests

deploy:
  provider: openshift
  domain: http://www.flaskapplication.com/
  on: 
   branch: master
    repo: flaskapplication
  app: 
    master: flaskapplication